// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAL-wH4dcRN4KA8MSBPZgxF7T0Y6VfTiBc',
    appId: '1:538942342322:android:0a29f9a5eeeac92dc675ab',
    messagingSenderId: '538942342322',
    projectId: 'dazzapp-e4537',
    databaseURL: 'https://dazzapp-e4537-default-rtdb.firebaseio.com',
    storageBucket: 'dazzapp-e4537.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtih_uoVuaGhlqmEny1G8tGaYtx81N0YE',
    appId: '1:538942342322:ios:8b6ec2274cd6dedfc675ab',
    messagingSenderId: '538942342322',
    projectId: 'dazzapp-e4537',
    databaseURL: 'https://dazzapp-e4537-default-rtdb.firebaseio.com',
    storageBucket: 'dazzapp-e4537.appspot.com',
    androidClientId: '538942342322-f3ibpiss4p9rht0ussb4sv5bd73pv585.apps.googleusercontent.com',
    iosClientId: '538942342322-4jtuadc36d48ighkg890nvk0s4lu85ck.apps.googleusercontent.com',
    iosBundleId: 'com.dazz.app',
  );
}
